apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
spec:
  template:
    spec:
      containers:
        - name: product-catalog
          env:
            - name: ENABLE_TRACING
              value: "false"
            - name: ENABLE_METRICS
              value: "false"
