# CNPG Cluster bootstrap + seed Job credentials (ns cnpg-banking).
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: banking-accounts-credentials
  namespace: cnpg-banking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-banking-platform
    kind: SecretStore
  target:
    name: banking-accounts-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: tiho-banking-platform/cnpg/accounts-creds
        property: username
    - secretKey: password
      remoteRef:
        key: tiho-banking-platform/cnpg/accounts-creds
        property: password
