apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
spec:
  template:
    spec:
      containers:
        - name: product-catalog
          env:
            - name: ENABLE_TRACING
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: product-catalog
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.observability.svc:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
