# Syncs Vault → K8s Secret ledger-db-secrets.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ledger-db-secrets
  namespace: banking-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-banking-platform
    kind: SecretStore
  target:
    name: ledger-db-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: tiho-banking-platform/db/ledger
        property: POSTGRES_PASSWORD
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: tiho-banking-platform/db/ledger
        property: SPRING_DATASOURCE_PASSWORD
