# Demo credentials — replace with External Secrets in production.
apiVersion: v1
kind: Secret
metadata:
  name: banking-accounts-credentials
  namespace: cnpg-banking
type: kubernetes.io/basic-auth
stringData:
  username: accounts-admin
  password: demo-password-change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: banking-ledger-credentials
  namespace: cnpg-banking
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: demo-password-change-me
