apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: banking-ledger
  namespace: cnpg-banking
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  bootstrap:
    initdb:
      database: postgresdb
      owner: admin
      secret:
        name: banking-ledger-credentials
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: banking-ledger-init-sql
            key: schema.sql
  storage:
    size: 1Gi
